### ISSUE TITLE
Strange string-to-gint64 conversion

### ISSUE THREAD

**Issue by jfsmig** [redcurrant/redcurrant#23]
Noticed at https://github.com/redcurrant/redcurrant/blob/master/client/c/lib/content_upload.c#L1206

PROPERTIES_set_alias_version(bp, ***(guint64)***hc_url_get(url, HCURL_VERSION));

A warning appeared despite the cast because of a size mismatch between the pointer size and the integer size (on a i386 architecture).

**Comment by jfsmig** [comment]
Idem at client/c/lib/contents.c:935:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   PROPERTIES_set_alias_version(bp, (guint64)hc_url_get(url, HCURL_VERSION));

**Comment by fvennetier** [comment]
Hello. For both cases, setting the `alias version` field of the property is not important since the server may change the alias version (in case the versioning is enabled). We can get rid of this line, but we need to fix the `alias version` field server-side.
